#!/usr/bin/env bash

# Program to output a system information page
TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"
PROGNAME="$(basename "$0")"

usage() {
    echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
    return
}
# process command line options
interactive=
filename=
while [[ -n "$1" ]]; do
    case "$1" in
    -f | --file)
        shift
        filename="$1"
        ;;
    -i | --interactive)
        interactive=1
        ;;
    -h | --help)
        usage
        exit
        ;;
    *)
        usage >&2
        exit 1
        ;;
    esac
    shift
done

# interactive mode
if [[ -n "$interactive" ]]; then
    while true; do
        read -p "Enter name of output file: " filename
        if [[ -e "$filename" ]]; then
            read -p "'$filename' exists. Overwrite? [y/n/q] > "
            case "$REPLY" in
            Y | y) break ;;
            Q | q)
                echo "Program terminated." exit
                ;;
            *)
                continue
                ;;
            esac
        elif [[ -z "$filename" ]]; then
            continue
        else
            break
        fi
    done
fi

report_uptime() {
    cat <<-_EOF_
            <h2>System Uptime</h2>
            <pre>$(uptime)</pre>
_EOF_
    return
}

report_home_space() {
    cat <<-_EOF_
        <h2>Home Space Utilization</h2>
        <pre>$(du -sh /home/*)</pre>
_EOF_
    return
}

report_disk_space() {
    cat <<-_EOF_
            <h2>Disk Space Utilization</h2>
            <pre>$(df -h)</pre>
_EOF_
    return
}

write_html_page() {
    cat <<_EOF_
<html>
  <head>
      <title>$TITLE</title>
  </head>
  <body>
         <h1>$TITLE</h1>
         <p>$TIMESTAMP</p>
         $(report_uptime)
         $(report_disk_space)
         $(report_home_space)
  </body>
</html>
_EOF_
}

if [[ -n "$filename" ]]; then
    if touch "$filename" && [[ -e "$filename" ]]; then
        write_html_page >"$filename"
    else
        echo "$PROGNAME: Failed to create output file $filename" >&2
        exit
    fi
else
    write_html_page
fi
