#!/usr/bin/env bash

# ul-declare: demonstrate case conversion via declare

declare -u upper
declare -l lower

if [[ -n "$1" ]]; then
    upper="$1"
    lower="$1"
    echo "$upper"
    echo "$lower"
fi