#!/opt/homebrew/bin/bash

# hours: script to count files by modification time

usage (){
    echo "usage: ${0##*/} directory" >& 2
}

#check that argument is a directory
if [[ ! -d "$1" ]]; then
    usage
    exit 1
fi

#initialize array
for i in {0..23}; do hours[i]=0; done

#collect data
for i in $(stat -t %H "$1"/* | cut -w -f 9); do 
    j=${i#\"}
    j=${j#0}
    j=${j/\"}
    ((++hours[${j}]))
done

# display data
echo "Hour Files"
echo "----  -----"
for i in {0..23}; do 
    printf "%02d\t%d\n" "$i" "${hours[i]}"
done