#!/usr/bin/env bash
# read-single: read multiple values into default variable
echo -n "Enter one or more values > "
read -e
# more compactly...
# read -p "Enter one or more values >"

echo "REPLY = '$REPLY'"